### ISSUE TITLE
line-height on About and Events is different

### ISSUE THREAD

**Issue by anbenson** [ScottyLabs/scottylabs.github.io#66]
If you compare the space between lines (which is what the CSS property line-height controls) for the About section and the Events section on https://scottylabs.org/, you'll notice they're significantly different. Now that you see it, you can't unsee it.

Looks like the issue is because the text for the About section is a `<p>` element, whereas the text for some of the other sections including Events are `<h3>` elements.

**Comment by crcmowry** [comment]
Thanks for bringing this up! I'll mention it to our director of design and see what he wants to do with it.

**Comment by ayoubmansar** [comment]
resolved: https://github.com/ScottyLabs/scottylabs.github.io/pull/72
